baseurl = "http://kursaufdiebretagne.github.io"
title = "Kurs auf die Bretagne"
theme = "mainroad"
defaultContentLanguage = "de"

[params]
  mainSections = ["blog", "posts"]
  customCSS = ["css/custom.css"]

[params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "languages"]

[params.logo]
  image = "img/logo.png"
  title = "Kurs auf die Bretagne"
  subtitle = "Stralsund & Saint-Malo"

# --- DEUTSCH ---
[languages.de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 1
  title = "Kurs auf die Bretagne"


[[languages.de.menu.main]]
  name = "Startseite"
  url = "/"
  weight = 1

[[languages.de.menu.main]]
  name = "Über uns"
  url = "/about/"
  weight = 2

[[languages.de.menu.main]]
  name = "Termine"
  url = "/events/"
  weight = 3

# --- FRANZÖSISCH ---
[languages.fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 2
  title = "Cap vers la Bretagne"

[[languages.fr.menu.main]]
  name = "Accueil"
  url = "/fr/"
  weight = 1

[[languages.fr.menu.main]]
  name = "À propos"
  url = "/fr/about/"
  weight = 2

[[languages.fr.menu.main]]
  name = "Événements"
  url = "/fr/events/"
  weight = 3
