baseurl = "https://kurs-bretagne.de/"
title = "Kurs auf die Bretagne"
theme = "mainroad"
defaultContentLanguage = "de"

[params]
  mainSections = ["blog", "posts"]
  customCSS = ["css/custom.css"]

[params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "languages"]

[params.logo]
  image = "img/logo.png"
  title = "Kurs auf die Bretagne"
  subtitle = "Stralsund & Saint-Malo"

# --- DEUTSCH ---
[languages.de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 1
  title = "Kurs auf die Bretagne"


[[languages.de.menu.main]]
  name = "Startseite"
  url = "/"
  weight = 1

[[languages.de.menu.main]]
  name = "Über uns"
  url = "/about/"
  weight = 3

[[languages.de.menu.main]]
  name = "Termine"
  url = "/events/"
  weight = 2

[[languages.de.menu.main]]
  name = "Kontakt"
  url = "/kontakt/"
  weight = 4


# --- FRANZÖSISCH ---
[languages.fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 2
  title = "Cap vers la Bretagne"

[[languages.fr.menu.main]]
  name = "Accueil"
  url = "/fr/"
  weight = 1

[[languages.fr.menu.main]]
  name = "À propos"
  url = "/fr/about/"
  weight = 3

[[languages.fr.menu.main]]
  name = "Événements"
  url = "/fr/events/"
  weight = 2

# ---- FOOTER ----

[[languages.de.menu.footer]]
  name = "Impressum"
  url = "/impressum/"
  weight = 1

[[languages.de.menu.footer]]
  name = "Datenschutz"
  url = "/datenschutz/"
  weight = 2

[[languages.fr.menu.footer]]
  name = "Mentions légales"
  url = "/fr/impressum/"
  weight = 1

[[languages.fr.menu.footer]]
  name = "Confidentialité"
  url = "/fr/datenschutz/"
  weight = 2

# --- HTML erlauben ---
[markup.goldmark.renderer]
  unsafe = true
